version: '3.7'
services:

  apigateway:
    image: deozza/appquarium-apigateway:4be8f90
    restart: on-failure
    user: '1000:1000'

  apiuser:
    image: deozza/appquarium-apiuser:96fb3c1
    restart: on-failure
    environment:
      MONGODB_URL: mongodb+srv://edenn:CmzVS2udbw9aRGJx@appquarium-microservice-rjsyh.mongodb.net/apiuser?retryWrites=true&w=majority
      MONGODB_DB: apiuser
      CORS_ALLOW_ORIGIN: '^https://apigateway.appquarium.fr$$'
    user: '1000:1000'

  apispecies:
    image: deozza/appquarium-apispecies:e51da8c
    restart: on-failure
    environment:
      MONGODB_URL: mongodb+srv://edenn:CmzVS2udbw9aRGJx@appquarium-microservice-rjsyh.mongodb.net/apispecies?retryWrites=true&w=majority
      MONGODB_DB: apispecies
      CORS_ALLOW_ORIGIN: '^https://apigateway.appquarium.fr$$'
    user: '1000:1000'

  nginx:
    image: deozza/appquarium-nginx
    restart: always
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - apigateway
      - apiuser
      - apispecies
    links:
      - apigateway
      - apiuser
      - apispecies
    ports:
      - 80:80
      - 443:443
