version: '3.7'
services:

  apigateway:
    image: deozza/appquarium-apigateway
    restart: on-failure
    environment:
      USER_BASE_URL: https://apiuser.appquarium.fr/
      SPECIES_BASE_URL: https://apispecies.appquarium.fr/
    user: '1000:1000'

  nginx:
    image: deozza/appquarium-nginx
    restart: always
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - apigateway
    links:
      - apigateway
    ports:
      - 8080:80
