version: '3.7'
services:

  apigateway:
    image: deozza/appquarium-apigateway
    restart: on-failure
    environment:
      USER_BASE_URL: https://apiuser.appquarium.fr/
      SPECIES_BASE_URL: https://apispecies.appquarium.fr/
    user: '1000:1000'

  apiuser:
    image: deozza/appquarium-apiuser
    restart: on-failure
    environment:
      MONGODB_URL: mongodb+srv://edenn:CmzVS2udbw9aRGJx@appquarium-microservice-rjsyh.mongodb.net/apiuser?retryWrites=true&w=majority
      MONGODB_DB: apiuser
      NETWORK_ACCESS: internal
    user: '1000:1000'

  apispecies:
    image: deozza/appquarium-apispecies
    restart: on-failure
    environment:
      MONGODB_URL: mongodb+srv://edenn:CmzVS2udbw9aRGJx@appquarium-microservice-rjsyh.mongodb.net/apispecies?retryWrites=true&w=majority
      MONGODB_DB: apispecies
    user: '1000:1000'

  nginx:
    image: deozza/appquarium-nginx
    restart: always
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - apigateway
      - apispecies
      - apiuser