version: '3.7'
services:

  apigateway:
    image: deozza/appquarium-apigateway
    container_name: appquarium.apigateway
    restart: on-failure
    environment:
      APP_ENV: prod
      USER_BASE_URL: http://local.apiuser.appquarium.fr/
      SPECIES_BASE_URL: http://local.apispecies.appquarium.fr/
    user: '1000:1000'

  apiuser:
    image: deozza/appquarium-apiuser
    container_name: appquarium.apiuser
    restart: on-failure
    environment:
      APP_ENV: prod
      MONGODB_URL: mongodb+srv://edenn:CmzVS2udbw9aRGJx@appquarium-microservice-rjsyh.mongodb.net/apiuser?retryWrites=true&w=majority
      MONGODB_DB: apiuser
    user: '1000:1000'

  apispecies:
    image: deozza/appquarium-apispecies
    container_name: appquarium.apispecies
    restart: on-failure
    environment:
      APP_ENV: prod
      MONGODB_URL: mongodb+srv://edenn:CmzVS2udbw9aRGJx@appquarium-microservice-rjsyh.mongodb.net/apispecies?retryWrites=true&w=majority
      MONGODB_DB: apispecies
    user: '1000:1000'

  nginx-proxy:
    image: deozza/appquarium-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: nginx-proxy
    depends_on:
      - apigateway
      - apispecies
      - apiuser
    ports:
      - 80:80
